import React, { useEffect, useState } from "react";

import axios from "axios";

import { motion } from "framer-motion";

import Head from "next/head";
import Post from "../../components/Post/Post";
import Comment from "../../components/Post/Comment";

const Index = ({ posts }) => {
  return (
    <motion.div
      initial={{ y: 100 }}
      animate={{ y: 0 }}
      transition={{ duration: 0.4 }}>
      <Head>
        <title>{posts.title} | Plain</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Post posts={posts} />
      <Comment />
    </motion.div>
  );
};

export const getServerSideProps = async (context) => {
  if (process.env.NODE_ENV === "development") {
    const res = await axios.get(
      `${process.env.DEV_URL}/api/post/${context.params.id}`
    );
    return { props: { posts: res.data } };
  } else {
    const res = await axios.get(
      `${process.env.PROD_URL}/api/post/${context.params.id}`
    );
    return { props: { posts: res.data } };
  }
};

export default Index;
